
== Building

=== Requirements
Tigase IoT Framework is based on the newest (not yet released) version of JaXMPP Bot Framework.
Due to that it is required to download sources of JaXMPP Bot Framework from the project available at https://tigase.tech/projects/jaxmpp-bot-framework and compile it.
For details about compilation of JaXMPP Bot Framework, please check the documentation of JaXMPP Bot Framework project.

=== Building Framework

Tigase IoT Framework binaries can be built with Gradle.

[source,bash]
----
./gradlew build publishToMavenLocal distZip
----

This line will compile whole framework (including Raspberry Pi releated stuff), install it to Gradle and Maven local repositories and create simplest possible bundle of a framework with only most necessary features.
This bundle will be created in a directory `runtime/build/distributions/`.

Additionally it will create a WAR archive with Tigase IoT Web Client in a directory `client/build/libs/`. File will be named `iot-client-2.0.0-SNAPSHOT.war`.

TIP: If you want want to start Tigase IoT Web Client locally without deploying it to a web server you may start it with `./gradlew gwtDev` which will start it using GWT development mode.
