
== Building

=== Requirements
Tigase IoT Framework is based on the newest (not yet released) version of JaXMPP Bot Framework.
Due to that it is required to download sources of JaXMPP Bot Framework from the project available at https://tigase.tech/projects/jaxmpp-bot-framework and compile it.
For details about compilation of JaXMPP Bot Framework, please check the documentation of JaXMPP Bot Framework project.

=== Building Framework

==== Gradle
Tigase IoT Framework binaries can be built with Gradle.

[source,bash]
----
./gradlew publish publishToMavenLocal distZip
----

This line will compile whole framework (including Raspberry Pi releated stuff), install it to Gradle and Maven repositories and create simplest possible bundle of a framework with only most necessary features.
This bundle will be created in a directory `runtime/build/distributions/`.

=== Building Web UI
Web UI for Tigase IoT Framework module which can be found in `client` subdirectory requires maven for building.

[source,bash]
-----
mvn package
-----

This will create WAR package in `target` subdirectory.
