
== Installation

Tigase IoT Framework distribution package comes with startup scripts for `systemd`.
To use them please follow this steps to install Tigase IoT Framework and `systemd` startup scripts.

=== Create user and adjust permissions

As the first step we need to create user with which permissions IoT framework will be running

[source,bash]
----
sudo useradd --home-dir /home/tigase --create-home --system tigase
----

If you are installing Tigase IoT Framework on Raspberry PI and want to use GPIO, SPI or I2C connected devices then we need to add newly created user to proper groups

[source,bash]
----
sudo usermod -a -G spi,i2c,gpio tigase
----

=== Switching working directory

For next steps we need to switch working directory to home directory of user `tigase`

[source,bash]
----
cd /home/tigase
----

=== Download distribution package

NOTE: We assume that you have `wget` utility installed.

We are going to change working directory to `tigase` user home path and download newest version of Tigase IoT Framework:

[source,bash]
----
sudo -u tigase wget http://build.tigase.org/nightlies/dists/latest/tigase-iot-framework.zip
----

=== Unpacking distribution package

To unpack distribution package and create symlink for easier access we are executing following commands:

[source,bash]
----
sudo -u tigase unzip tigase-iot-framework.zip
sudo -u tigase ln -s tigase-iot-framework-2.0.0-SNAPSHOT-b62 tigase-iot-framework
----

WARNING: We assumed that `tigase-iot-framework-2.0.0-SNAPSHOT-b62` is name of the directory unpacked from `tigase-iot-framework.zip`.

=== Installation of startup scripts

[source,bash]
----
sudo cp -r tigase-iot-framework/etc/default/* /etc/default/
sudo cp -r tigase-iot-framework/etc/systemd/* /etc/systemd/

sudo systemctl daemon-reload
----

=== Enabling Tigase IoT Framework 

[source,bash]
----
sudo systemctl enable tigase-iot-framework
----


=== Summary

At this point we have Tigase IoT Framework installed and configured to start after restart. From now on we can:

==== Start framework
[source,bash]
---- 
sudo systemctl start tigase-iot-framework
----

==== Stop framework
[source,bash]
----
sudo systemctl stop tigase-iot-framework
----

==== Check status of the framework
[source,bash]
----
sudo systemctl status tigase-iot-framework
----
