
== Requirements

There are a few requirement to use this project:

=== Device running IoT-XMPP bridge footnote:[Application which is based on Tigase IoT Framework and connects (creates bridge) IoT unaware sensors and allows them to access XMPP network] - Raspberry Pi
During our work we were using Raspbbery Pi 3 as a development device (due to already working and built-in WiFi), however project should work with any Raspberry Pi version.

[NOTE]
It is possible to use this project with other devices than Raspberry Pi as only `devices` module requires Raspbbery Pi to communicate with executor devices and sensors.
You can provide your support for other platforms by providing alternative implementations of drivers.

=== Tigase IoT Hub
It is required to use http://tigase.tech/projects/iot-xmpp-hub/[Tigase IoT Hub].  We recommend usage of the newest available version.
Tigase IoT Hub is a modified version of Tigase XMPP Server with PubSub component which has ready to use configuration and many improvements making usage of IoT Hub and this framework a lot easier.

[[xmpp-server-configuration]]
==== Configuration
Configuration of Tigase IoT Hub is stored in `etc/config.tdsl` file in DSL format and ready to use. You should not need to make any changes there.

However it is possible and configuration of Tigase XMPP Server is described in http://docs.tigase.org/[Tigase XMPP Server Administation Guide].

=== Network
A properly set up network on a Raspbbery Pi device with working connectivity to Tigase IoT Hub is required. Tigase IoT Hub and Tigase IoT Framework need to be connected to the same network.
