
== Running

=== Requirements
Tigase IoT Framework requires Tigase IoT Hub to be installed and running in the same network as Tigase IoT Framework.
IoT Framework may be started before IoT Hub but it will not be operational as for configuration and management IoT Hub is required.
For details about Tigase IoT Hub installation and configuration please check Tigase IoT Hub documentation.

[running]
=== Running framework
Unpack the distribution zip file you created during the build process, then navigate to the directory where it is unpacked.
Now we may run the bot.

[source,bash]
----
$ cd tigase-iot-framework-2.0.0-SNAPSHOT/
$ $ ./bin/tigase-iot-framework
2016-11-14 10:55:21.716 [main]             Kernel.createNewInstance()         FINER:    [root] Creating instance of bean defaultBeanConfigurator
2016-11-14 10:55:21.760 [main]             Kernel.createNewInstance()         FINER:    [root] Creating instance of bean defaultTypesConverter
2016-11-14 10:55:21.761 [main]             Kernel.injectDependencies()        FINER:    [root] Injecting [tigase.bot.runtime.CustomTypesConverter@304a9d7b] to defaultBeanConfigurator:tigase.component.DSLBeanConfigurator#bean:defaultTypesConverter
...
----                                  \

INFO: At this point you need to have a running Tigase IoT Hub connected to the same network.

Tigase IoT Framework runtime understands some variables that can control it, they may be displayed using the --help switch.

[source,bash]
----
$ ./bin/tigase-iot-framework --help
usage: tigase-iot-framework [options]

Options:
-h, --help                                   display this screen
-v, --version                                display version
-log, --logger-config <file>                 logger configuration file
-D<key=value>,[key=value]                    set system property

----

Configuration of the bot framework will be store in config file, what is DSL file, at `etc/config.tdsl`.
There is no need to manually edit this file or prepare configuration, as IoT Framework will find local Tigase IoT Hub and automatically register in it and generate configuration for later usage.

=== Running Web UI
Package created during build of Web UI may be deployed to any Java based HTTP server (like ie. Tomcat) or it is possible to unzip content of this archive to any subdirectory and point web server like Apache or NGINX to this directory for serving data.

It is also possible to start Web UI without any web server by running following command:

[source,bash]
-----
mvn gwt:run
-----

This will start web UI using GWT SuperDevMode.

[NOTE]
It is required to build base part of a project with Gradle before building Web UI with Maven.

[NOTE]
It is best to have Web UI deployed on same server which hosts Tigase XMPP Server (HUB).
